print("Reglas básicas de Monopoly:")
print("1. El objetivo del juego es acumular la mayor cantidad de dinero y propiedades.")
print("2. Cada jugador comienza con una cantidad de dinero y un peón.")
print("3. Los jugadores se turnan para lanzar dos dados y mover su peón por el tablero.")
print("4. Si caes en una propiedad que no está comprada, puedes comprarla o subastarla.")
print("5. Si caes en una propiedad comprada por otro jugador, debes pagarle alquiler.")
print("6. Si caes en una casilla de suerte o comunidad, sigue las instrucciones de la carta.")
print("7. Si caes en una casilla de impuesto, debes pagar la cantidad indicada.")
print("8. Si no puedes pagar una deuda, puedes hipotecar propiedades o declarar bancarrota.")
print("9. Puedes construir casas y hoteles en tus propiedades para aumentar el alquiler.")
print("10. El juego termina cuando un jugador quiebra a todos los demás o se alcanza un tiempo límite acordado.")