#Crea un archivo llamado ejercicio_03.py y utilizando múltiples print realiza un tutorial de como lavar los platos, se lo más detallado posible indica desde que tipo de esponja utilizar hasta el orden en que se lava y como secar los platos.
print("Tutorial: Cómo lavar los platos")
print("Paso 1: Reúne los materiales necesarios.")
print(" - Esponja suave o esponja de acero (dependiendo del tipo de platos).")
print(" - Detergente para platos.")
print(" - Agua caliente.")
print(" - Un estropajo o cepillo para platos (opcional).")
print(" - Un escurridor o toalla de cocina.")
print("Paso 2: Retira los restos de comida.")
print(" - Con una espátula o cuchara, raspa los restos de comida de los platos.")
print("Paso 3: Llena el fregadero con agua caliente.")
print(" - Asegúrate de que el agua esté caliente, pero no hirviendo.")
print("Paso 4: Agrega detergente al agua.")
print(" - Añade una cantidad adecuada de detergente para platos al agua.")
print("Paso 5: Sumerge los platos en el agua jabonosa.")
print(" - Deja que los platos se empapen durante unos minutos.")
print("Paso 6: Lava los platos.")
print(" - Usa la esponja suave para frotar los platos, comenzando por los menos sucios.")
print(" - Si es necesario, utiliza el estropajo o cepillo para platos en las áreas más difíciles.")
print("Paso 7: Enjuaga los platos.")
print(" - Enjuaga cada plato con agua caliente para eliminar el detergente.")
print("Paso 8: Coloca los platos en el escurridor.")
print(" - Asegúrate de que estén bien separados para que se sequen más rápido.")
print("Paso 9: Seca los platos.")
print(" - Usa una toalla de cocina limpia para secar los platos o déjalos escurrir al aire.")
